version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
       POSTGRES_PASSWORD: 'docker'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment: 
      PGADMIN_DEFAULT_EMAIL: 'user@email.com'
      PGADMIN_DEFAULT_PASSWORD: '123'
